In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../data/raw_ecommerce_events.csv')
df_processed = pd.read_csv('../data/preprocessed_ecommerce_events.csv')

In [3]:
df.head()

,event_id,session_id,client_timestamp,server_timestamp,event_date,user_id,anonymous_id,persona,event_type,page_type,...,product_brand,merchant_id,unit_price,cart_id,error_type,error_code,error_message,device_type,user_agent,payload
0,evt_b4be4a92b43f4519b643a95dc09bc6aa,sess_frus_000_1a3d1fa7,2026-10-03T09:29:07.632Z,2026-10-03T09:29:07.658Z,2026-10-03,usr_21395,anon_8b9d2434e465,frustration,page_view,home,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mobile,Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like M...,NaN
1,evt_a937f11a404c4a468f09f5f503f0dae0,sess_frus_000_1a3d1fa7,2026-10-03T09:29:08.893Z,2026-10-03T09:29:08.966Z,2026-10-03,usr_21395,anon_8b9d2434e465,frustration,scroll_checkpoint,home,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mobile,Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like M...,"{""scroll_depth_percent"": 3}"
2,evt_4d797031ac774653897317e101a122de,sess_frus_000_1a3d1fa7,2026-10-03T09:29:10.210Z,2026-10-03T09:29:10.382Z,2026-10-03,usr_21395,anon_8b9d2434e465,frustration,search,search,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mobile,Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like M...,NaN
3,evt_57a2d184c1214a4f9d51fef26044d5e8,sess_frus_000_1a3d1fa7,2026-10-03T09:29:10.210Z,2026-10-03T09:29:10.234Z,2026-10-03,usr_21395,anon_8b9d2434e465,frustration,page_view,search,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mobile,Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like M...,NaN
4,evt_4e25d38c569741c09e4c7d39ad12fd66,sess_frus_000_1a3d1fa7,2026-10-03T09:29:13.524Z,2026-10-03T09:29:13.598Z,2026-10-03,usr_21395,anon_8b9d2434e465,frustration,click,search,...,Nothing,xkom,1449.0,NaN,NaN,NaN,NaN,mobile,Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like M...,NaN

In [5]:
df_processed.head()

,event_id,session_id,event_seq,timestamp,persona,user_id,anonymous_id,page_type,page_title,action_type,...,zero_result_searches,last_error_code,last_error_message,most_frequent_friction,active_filters,compared_products_count,current_product_name,current_product_price,cart_value,narrative_summary
0,evt_b4be4a92b43f4519b643a95dc09bc6aa,sess_frus_000_1a3d1fa7,1,2026-10-03T09:29:07.632000Z,frustration,usr_21395,anon_8b9d2434e465,home,Ceneo - porównywarka cen,PAGE_VIEW,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Otwarto stronę Ceneo - porównywarka cen.
1,evt_a937f11a404c4a468f09f5f503f0dae0,sess_frus_000_1a3d1fa7,2,2026-10-03T09:29:08.893000Z,frustration,usr_21395,anon_8b9d2434e465,home,Ceneo - porównywarka cen,SCROLL,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Przewinięto stronę 'Ceneo - porównywarka cen' ...
2,evt_4d797031ac774653897317e101a122de,sess_frus_000_1a3d1fa7,3,2026-10-03T09:29:10.210000Z,frustration,usr_21395,anon_8b9d2434e465,search,Szukaj: smartfon samsung 5g - Ceneo,SEARCH_QUERY,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,"Wyszukano ""smartfon samsung 5g"" (28 wyników)."
3,evt_57a2d184c1214a4f9d51fef26044d5e8,sess_frus_000_1a3d1fa7,4,2026-10-03T09:29:10.210000Z,frustration,usr_21395,anon_8b9d2434e465,search,Szukaj: smartfon samsung 5g - Ceneo,PAGE_VIEW,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Otwarto stronę Szukaj: smartfon samsung 5g - C...
4,evt_4e25d38c569741c09e4c7d39ad12fd66,sess_frus_000_1a3d1fa7,5,2026-10-03T09:29:13.524000Z,frustration,usr_21395,anon_8b9d2434e465,search,Szukaj: smartfon samsung 5g - Ceneo,PRICE_COMPARISON_CLICK,...,0,NaN,NaN,NaN,NaN,0,Nothing Phone (2a) 256GB,1449.0,NaN,Kliknięto ofertę Nothing Phone (2a) 256GB.